/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:39
-- bootstrap
-- First statement of installation and of the 0.0.0 -> 0.0.1 update.
-- Extension scripts run this even when preload hooks are absent, the
-- firewall is disabled, or superuser bypass is on. Failure aborts the
-- extension transaction, so a rejected install leaves no objects and a
-- rejected update leaves the previous version in place.
DO $sqlfw_utf8$
BEGIN
    IF pg_catalog.current_setting('server_encoding')
        OPERATOR(pg_catalog.<>) 'UTF8'::pg_catalog.text
    THEN
        RAISE EXCEPTION
            'sql_firewall: UTF8 database encoding is required; server_encoding is %',
            pg_catalog.current_setting('server_encoding')
            USING ERRCODE = '0A000';
    END IF;
END
$sqlfw_utf8$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:44
-- Core tables for sql_firewall. These definitions mirror the legacy C extension
-- but grant the necessary privileges so any role can interact with the firewall.

CREATE TABLE IF NOT EXISTS public.sql_firewall_activity_log (
    log_id           SERIAL PRIMARY KEY,
    log_time         TIMESTAMPTZ DEFAULT now() NOT NULL,
    role_name        NAME,
    database_name    NAME,
    query_text       TEXT,
    application_name TEXT,
    client_ip        TEXT,
    command_type     TEXT,
    action           TEXT,
    reason           TEXT
);

COMMENT ON TABLE  public.sql_firewall_activity_log IS 'Log of all actions performed by the SQL Firewall.';
COMMENT ON COLUMN public.sql_firewall_activity_log.action IS 'Action performed: ALLOWED, BLOCKED, LEARNED, etc.';
COMMENT ON COLUMN public.sql_firewall_activity_log.reason IS 'Reason for the action: Rate limit, blacklisted keyword, etc.';

ALTER TABLE public.sql_firewall_activity_log SET LOGGED;

CREATE INDEX IF NOT EXISTS idx_sqlfw_activity_role_time
    ON public.sql_firewall_activity_log(role_name, log_time);
CREATE INDEX IF NOT EXISTS idx_sqlfw_activity_role_cmd_time
    ON public.sql_firewall_activity_log(role_name, command_type, log_time);
CREATE INDEX IF NOT EXISTS idx_sqlfw_activity_action
    ON public.sql_firewall_activity_log(action);

-- SECURITY: No direct grants to PUBLIC - all access through SECURITY DEFINER functions
-- This prevents users from tampering with firewall logs and configuration

-- Dedicated table for blocked queries - separate from activity log for security analysis
-- ENHANCED: Now with 2KB query buffer, truncation flag, and richer metadata
CREATE TABLE IF NOT EXISTS public.sql_firewall_blocked_queries (
    block_id         SERIAL PRIMARY KEY,
    blocked_at       TIMESTAMPTZ DEFAULT now() NOT NULL,
    role_name        NAME,
    database_name    NAME,
    query_text       TEXT,               -- Up to 2KB query text (enforced by ring buffer)
    query_truncated  BOOLEAN DEFAULT false, -- True if query was larger than 2KB
    application_name TEXT,
    client_addr      TEXT,               -- Renamed from client_ip for consistency
    command_type     TEXT,
    reason           TEXT                -- Renamed from block_reason for consistency with activity log
);

COMMENT ON TABLE  public.sql_firewall_blocked_queries IS 'Dedicated log for blocked queries - useful for security analysis and auditing.';
COMMENT ON COLUMN public.sql_firewall_blocked_queries.query_truncated IS 'True if query was truncated at 2KB limit during capture.';
COMMENT ON COLUMN public.sql_firewall_blocked_queries.reason IS 'Reason why the query was blocked: No approval, regex match, rate limit, etc.';

ALTER TABLE public.sql_firewall_blocked_queries SET LOGGED;

CREATE INDEX IF NOT EXISTS idx_sqlfw_blocked_role_time
    ON public.sql_firewall_blocked_queries(role_name, blocked_at);
CREATE INDEX IF NOT EXISTS idx_sqlfw_blocked_command_time
    ON public.sql_firewall_blocked_queries(command_type, blocked_at);

-- SECURITY: No direct grants to PUBLIC - all access through SECURITY DEFINER functions
-- This prevents users from tampering with security audit logs

-- ENHANCED: is_approved column tracks whether approval was granted or pending
CREATE TABLE IF NOT EXISTS public.sql_firewall_command_approvals (
    id           SERIAL PRIMARY KEY,
    role_name    NAME        NOT NULL,
    command_type TEXT        NOT NULL,
    is_approved  BOOLEAN     NOT NULL DEFAULT false,  -- TRUE = approved, FALSE = pending admin review
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),  -- Track when approval status last changed
    UNIQUE (role_name, command_type)
);

COMMENT ON TABLE  public.sql_firewall_command_approvals IS 'Approval status of command types per role.';
COMMENT ON COLUMN public.sql_firewall_command_approvals.is_approved IS 'If true, this role is allowed to execute the command type. If false, approval is pending admin review.';
COMMENT ON COLUMN public.sql_firewall_command_approvals.updated_at IS 'Timestamp when approval status was last changed (useful for auditing approval grants).';

-- SECURITY: No direct grants to PUBLIC - all access through SECURITY DEFINER functions
-- This prevents users from approving their own commands

CREATE TABLE IF NOT EXISTS public.sql_firewall_regex_rules (
    id            SERIAL PRIMARY KEY,
    pattern       TEXT    NOT NULL UNIQUE,
    description   TEXT,
    action        TEXT    NOT NULL DEFAULT 'BLOCK' CHECK (action = 'BLOCK'),
    is_active     BOOLEAN NOT NULL DEFAULT true,
    allowed_roles TEXT[], -- NULL means rule applies to all roles, non-NULL means rule only applies to listed roles
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.sql_firewall_regex_rules IS 'Regex rules used to match and block SQL queries.';
COMMENT ON COLUMN public.sql_firewall_regex_rules.pattern IS 'Regex pattern to apply on the query text.';
COMMENT ON COLUMN public.sql_firewall_regex_rules.allowed_roles IS 'List of roles for which this rule applies. NULL means applies to all roles.';

-- CRITICAL: Validate regex patterns to prevent ReDoS attacks
CREATE OR REPLACE FUNCTION validate_firewall_regex_pattern()
RETURNS TRIGGER AS $$
BEGIN
    -- Check for dangerous patterns that can cause ReDoS
    IF NEW.pattern ~ '.*\(\?.*\{.*\}.*\).*' THEN
        RAISE EXCEPTION 'Complex nested quantifiers not allowed (ReDoS risk)';
    END IF;
    
    -- Check for excessive repetition operators
    IF NEW.pattern ~ '.*((\+\+)|(\*\*)|(\+\*)).*' THEN
        RAISE EXCEPTION 'Multiple adjacent quantifiers not allowed (ReDoS risk)';
    END IF;
    
    -- Test pattern with a simple string to ensure it's valid
    BEGIN
        PERFORM 'test' ~ NEW.pattern;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'Invalid regex pattern: %', SQLERRM;
    END;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER validate_regex_trigger
BEFORE INSERT OR UPDATE ON public.sql_firewall_regex_rules
FOR EACH ROW EXECUTE FUNCTION validate_firewall_regex_pattern();

-- SECURITY: No direct grants to PUBLIC - all access through admin functions
-- Users can query via SECURITY DEFINER functions but cannot modify

INSERT INTO public.sql_firewall_regex_rules (pattern, description)
SELECT '(or|--|#)\s+([[:alpha:]_][[:alnum:]_]*|''[^'']*''|[0-9]+)\s*=\s*([[:alpha:]_][[:alnum:]_]*|''[^'']*''|[0-9]+)', 'Block simple SQL injection pattern'
WHERE NOT EXISTS (
    SELECT 1 FROM public.sql_firewall_regex_rules WHERE pattern = '(or|--|#)\s+([[:alpha:]_][[:alnum:]_]*|''[^'']*''|[0-9]+)\s*=\s*([[:alpha:]_][[:alnum:]_]*|''[^'']*''|[0-9]+)'
);

CREATE TABLE IF NOT EXISTS public.sql_firewall_query_fingerprints (
    id               SERIAL PRIMARY KEY,
    fingerprint      TEXT        NOT NULL,
    normalized_query TEXT        NOT NULL,
    role_name        NAME        NOT NULL,
    command_type     TEXT        NOT NULL,
    sample_query     TEXT        NOT NULL,
    hit_count        INTEGER     NOT NULL DEFAULT 1,
    is_approved      BOOLEAN     NOT NULL DEFAULT false,
    first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (fingerprint, role_name, command_type)
);

COMMENT ON TABLE  public.sql_firewall_query_fingerprints IS 'Normalized query fingerprints tracked per role.';
COMMENT ON COLUMN public.sql_firewall_query_fingerprints.hit_count IS 'Number of times this fingerprint has been observed.';
COMMENT ON COLUMN public.sql_firewall_query_fingerprints.is_approved IS 'If true, queries matching this fingerprint are allowed.';
COMMENT ON COLUMN public.sql_firewall_query_fingerprints.first_seen_at IS 'Timestamp when this fingerprint was first recorded.';
COMMENT ON COLUMN public.sql_firewall_query_fingerprints.last_seen_at IS 'Timestamp when this fingerprint was last observed.';

CREATE INDEX IF NOT EXISTS idx_sqlfw_fingerprint_role
    ON public.sql_firewall_query_fingerprints(role_name, fingerprint);
CREATE INDEX IF NOT EXISTS idx_sqlfw_fingerprint_last_seen
    ON public.sql_firewall_query_fingerprints(last_seen_at);

-- SECURITY: No direct grants to PUBLIC - all access through SECURITY DEFINER functions
-- This prevents users from tampering with learned fingerprints

-- NEW: Fingerprint hits table for background worker event processing
CREATE TABLE IF NOT EXISTS public.sql_firewall_fingerprint_hits (
    fingerprint      TEXT PRIMARY KEY,
    normalized_query TEXT        NOT NULL,
    role_name        NAME,
    command_type     TEXT,
    sample_query     TEXT,
    hit_count        BIGINT      NOT NULL DEFAULT 1,
    is_approved      BOOLEAN     NOT NULL DEFAULT false,
    first_hit_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_hit_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.sql_firewall_fingerprint_hits IS 'Fingerprint hit tracking populated by background worker from ring buffer events.';
COMMENT ON COLUMN public.sql_firewall_fingerprint_hits.hit_count IS 'Number of times this fingerprint has been observed (incremented by ON CONFLICT).';
COMMENT ON COLUMN public.sql_firewall_fingerprint_hits.is_approved IS 'If true, queries matching this fingerprint are allowed.';

CREATE INDEX IF NOT EXISTS idx_sqlfw_fphits_approved
    ON public.sql_firewall_fingerprint_hits(is_approved, hit_count DESC);
CREATE INDEX IF NOT EXISTS idx_sqlfw_fphits_last_hit
    ON public.sql_firewall_fingerprint_hits(last_hit_at DESC);

-- SECURITY: No direct grants to PUBLIC - all access through SECURITY DEFINER functions

-- ============================================================================
-- SECURITY DEFINER Functions for Controlled Admin Access
-- ============================================================================
-- These management functions authorize session_user via pg_catalog.pg_authid
-- (rolsuper is the column behind pg_user.usesuper). Each sets
-- search_path = pg_catalog, pg_temp, with pg_temp listed explicitly and last.
-- If pg_temp is omitted, PostgreSQL searches it before pg_catalog for relations.
-- Extension tables are schema-qualified. Standard types and operators then
-- resolve in pg_catalog; pg_temp is not searched for operators.

-- Function to approve a command for a role (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_approve_command(
    p_role_name NAME,
    p_command_type TEXT
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can approve commands'
            USING ERRCODE = '42501';
    END IF;
    
    INSERT INTO public.sql_firewall_command_approvals (role_name, command_type, is_approved)
    VALUES (p_role_name, p_command_type, true)
    ON CONFLICT (role_name, command_type) 
    DO UPDATE SET is_approved = true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

COMMENT ON FUNCTION public.sql_firewall_approve_command IS 
'Approve a command type for a specific role. Only callable by superusers.';

-- Function to revoke command approval (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_revoke_command(
    p_role_name NAME,
    p_command_type TEXT
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can revoke commands'
            USING ERRCODE = '42501';
    END IF;
    
    UPDATE public.sql_firewall_command_approvals
    SET is_approved = false
    WHERE role_name = p_role_name AND command_type = p_command_type;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Function to approve a fingerprint (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_approve_fingerprint(
    p_fingerprint TEXT,
    p_role_name NAME,
    p_command_type TEXT
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can approve fingerprints'
            USING ERRCODE = '42501';
    END IF;
    
    UPDATE public.sql_firewall_query_fingerprints
    SET is_approved = true
    WHERE fingerprint = p_fingerprint 
      AND role_name = p_role_name 
      AND command_type = p_command_type;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Function to block a fingerprint (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_block_fingerprint(
    p_fingerprint TEXT,
    p_role_name NAME,
    p_command_type TEXT
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can block fingerprints'
            USING ERRCODE = '42501';
    END IF;
    
    UPDATE public.sql_firewall_query_fingerprints
    SET is_approved = false
    WHERE fingerprint = p_fingerprint 
      AND role_name = p_role_name 
      AND command_type = p_command_type;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Function to add a regex rule (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_add_regex_rule(
    p_pattern TEXT,
    p_description TEXT DEFAULT NULL
) RETURNS INTEGER AS $$
DECLARE
    v_rule_id INTEGER;
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can add regex rules'
            USING ERRCODE = '42501';
    END IF;
    
    INSERT INTO public.sql_firewall_regex_rules (pattern, description)
    VALUES (p_pattern, p_description)
    RETURNING id INTO v_rule_id;
    
    RETURN v_rule_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Function to delete a regex rule (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_delete_regex_rule(
    p_rule_id INTEGER
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can delete regex rules'
            USING ERRCODE = '42501';
    END IF;
    
    DELETE FROM public.sql_firewall_regex_rules
    WHERE id = p_rule_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Function to toggle regex rule active status (only superusers can call this)
CREATE OR REPLACE FUNCTION public.sql_firewall_toggle_regex_rule(
    p_rule_id INTEGER,
    p_is_active BOOLEAN
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can modify regex rules'
            USING ERRCODE = '42501';
    END IF;
    
    UPDATE public.sql_firewall_regex_rules
    SET is_active = p_is_active
    WHERE id = p_rule_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- Superuser-only management functions. PostgreSQL grants EXECUTE to PUBLIC
-- by default, so removing a GRANT is not enough: revoke it. The bodies above
-- still reject a non-superuser (SQLSTATE 42501) if EXECUTE is granted later.
-- No separate administrative role is introduced.
REVOKE ALL ON FUNCTION public.sql_firewall_approve_command(NAME, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_revoke_command(NAME, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_approve_fingerprint(TEXT, NAME, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_block_fingerprint(TEXT, NAME, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_add_regex_rule(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_delete_regex_rule(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_toggle_regex_rule(INTEGER, BOOLEAN) FROM PUBLIC;


-- ============================================================================
-- SECURITY DEFINER Wrappers for Extension Internal Operations
-- ============================================================================
-- These functions allow the extension to write to catalog tables
-- without granting INSERT/UPDATE/DELETE to PUBLIC

-- Log activity (called by extension internally)
CREATE OR REPLACE FUNCTION public.sql_firewall_internal_log_activity(
    p_role_name NAME,
    p_database_name NAME,
    p_query_text TEXT,
    p_application_name TEXT,
    p_client_ip TEXT,
    p_command_type TEXT,
    p_action TEXT,
    p_reason TEXT
) RETURNS VOID AS $$
DECLARE
    v_role NAME := p_role_name;
BEGIN
    -- SECURITY: this function must stay callable by PUBLIC because every backend
    -- writes its own activity rows through it. It therefore must NOT trust the
    -- identity the caller passes in: previously any role could forge a row
    -- attributed to another role (e.g. 'postgres').
    --
    -- Superusers (the background worker) may log on behalf of any role. Everyone
    -- else may only log as a role they could actually act as - session_user or a
    -- role they are a member of, which covers SET ROLE.
    IF NOT (SELECT usesuper FROM pg_catalog.pg_user WHERE usename = session_user) THEN
        -- NOTE: the pg_roles existence test must come first. pg_has_role()
        -- RAISES for a role name that does not exist, which would turn a forged
        -- (or merely stale) role name into a failed statement instead of a
        -- correctly attributed log row.
        IF v_role IS NULL
           OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = v_role)
           OR NOT pg_catalog.pg_has_role(session_user, v_role, 'MEMBER')
        THEN
            v_role := session_user;
        END IF;
    END IF;

    INSERT INTO public.sql_firewall_activity_log (
        role_name, database_name, query_text, application_name,
        client_ip, command_type, action, reason
    ) VALUES (
        v_role, current_database(), p_query_text, p_application_name,
        p_client_ip, p_command_type, p_action, p_reason
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public;

-- Log blocked query to dedicated table (called by extension internally)
CREATE OR REPLACE FUNCTION public.sql_firewall_internal_log_blocked_query(
    p_role_name NAME,
    p_database_name NAME,
    p_query_text TEXT,
    p_application_name TEXT,
    p_client_ip TEXT,
    p_command_type TEXT,
    p_block_reason TEXT
) RETURNS VOID AS $$
DECLARE
    v_conn TEXT;
    v_result TEXT;
BEGIN
    -- Use dblink to perform autonomous transaction that survives rollback
    -- This ensures blocked queries are logged even when the main transaction aborts
    BEGIN
        -- Connect to current database using dblink (safely quote database name)
        v_conn := 'dbname=' || quote_ident(current_database());
        PERFORM dblink_connect('firewall_log_conn', v_conn);
        
        -- Execute INSERT in autonomous transaction
        PERFORM dblink_exec('firewall_log_conn',
            format('INSERT INTO public.sql_firewall_blocked_queries 
                (role_name, database_name, query_text, application_name, client_addr, command_type, reason) 
                VALUES (%L, %L, %L, %L, %L, %L, %L)',
                p_role_name, p_database_name, p_query_text, p_application_name,
                p_client_ip, p_command_type, p_block_reason
            )
        );
        
        -- Disconnect dblink
        PERFORM dblink_disconnect('firewall_log_conn');
    EXCEPTION WHEN OTHERS THEN
        -- If dblink fails, fall back to regular INSERT (which may rollback)
        BEGIN
            PERFORM dblink_disconnect('firewall_log_conn');
        EXCEPTION WHEN OTHERS THEN
            -- Ignore disconnect errors
        END;
        
        -- Fallback: regular insert (will rollback with transaction)
        INSERT INTO public.sql_firewall_blocked_queries (
            role_name, database_name, query_text, application_name,
            client_addr, command_type, reason
        ) VALUES (
            p_role_name, p_database_name, p_query_text, p_application_name,
            p_client_ip, p_command_type, p_block_reason
        );
    END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Record or update fingerprint (called by extension internally)
CREATE OR REPLACE FUNCTION public.sql_firewall_internal_upsert_fingerprint(
    p_fingerprint TEXT,
    p_normalized_query TEXT,
    p_role_name NAME,
    p_command_type TEXT,
    p_sample_query TEXT,
    p_is_approved BOOLEAN
) RETURNS VOID AS $$
BEGIN
    INSERT INTO public.sql_firewall_query_fingerprints (
        fingerprint, normalized_query, role_name, command_type,
        sample_query, hit_count, is_approved, last_seen_at
    ) VALUES (
        p_fingerprint, p_normalized_query, p_role_name, p_command_type,
        p_sample_query, 1, p_is_approved, now()
    )
    ON CONFLICT (fingerprint, role_name, command_type) DO UPDATE
    SET hit_count = sql_firewall_query_fingerprints.hit_count + 1,
        last_seen_at = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create or update approval (called by extension internally)
CREATE OR REPLACE FUNCTION public.sql_firewall_internal_upsert_approval(
    p_role_name NAME,
    p_command_type TEXT,
    p_is_approved BOOLEAN
) RETURNS VOID AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can use this internal function'
            USING ERRCODE = '42501';
    END IF;
    
    INSERT INTO public.sql_firewall_command_approvals (
        role_name, command_type, is_approved
    ) VALUES (
        p_role_name, p_command_type, p_is_approved
    )
    ON CONFLICT (role_name, command_type) DO UPDATE
    SET is_approved = p_is_approved;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

-- SECURITY: PostgreSQL grants EXECUTE to PUBLIC by default, so each function
-- must be revoked explicitly. Removing a GRANT line is not enough.
--
-- Only sql_firewall_internal_log_activity stays callable by PUBLIC: backends
-- write their own audit rows through it, and its body no longer trusts the
-- identity passed in (see above).
--
-- The other three were callable by any role with no privilege check at all:
--   * upsert_fingerprint let a user approve their own query fingerprint
--   * log_blocked_query let a user forge blocked-query records
--   * upsert_approval is only ever called by the background worker
-- log_blocked_query and upsert_fingerprint have no caller in the extension at
-- all (the worker INSERTs directly); they are kept only for compatibility.
REVOKE ALL ON FUNCTION public.sql_firewall_internal_log_activity(NAME, NAME, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_internal_log_blocked_query(NAME, NAME, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_internal_upsert_fingerprint(TEXT, TEXT, NAME, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_internal_upsert_approval(NAME, TEXT, BOOLEAN) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.sql_firewall_internal_log_activity(NAME, NAME, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO PUBLIC;

-- ========================================
-- LOG CLEANUP FUNCTIONS
-- ========================================

-- Clean activity log entries older than specified interval
CREATE OR REPLACE FUNCTION public.sql_firewall_cleanup_activity_log(
    p_retention_interval INTERVAL DEFAULT '30 days'
)
RETURNS TABLE(deleted_count BIGINT) AS $$
DECLARE
    v_deleted_count BIGINT;
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can cleanup firewall logs'
            USING ERRCODE = '42501';
    END IF;
    
    DELETE FROM public.sql_firewall_activity_log
    WHERE log_time < (pg_catalog.now() - p_retention_interval);
    
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    
    RETURN QUERY SELECT v_deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

COMMENT ON FUNCTION public.sql_firewall_cleanup_activity_log(INTERVAL) IS 
'Delete activity log entries older than specified interval. Default: 30 days. Superuser only.';

-- Clean blocked queries log entries older than specified interval
CREATE OR REPLACE FUNCTION public.sql_firewall_cleanup_blocked_queries(
    p_retention_interval INTERVAL DEFAULT '90 days'
)
RETURNS TABLE(deleted_count BIGINT) AS $$
DECLARE
    v_deleted_count BIGINT;
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can cleanup firewall logs'
            USING ERRCODE = '42501';
    END IF;
    
    DELETE FROM public.sql_firewall_blocked_queries
    WHERE blocked_at < (pg_catalog.now() - p_retention_interval);
    
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    
    RETURN QUERY SELECT v_deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

COMMENT ON FUNCTION public.sql_firewall_cleanup_blocked_queries(INTERVAL) IS 
'Delete blocked query log entries older than specified interval. Default: 90 days (longer retention for security analysis). Superuser only.';

-- Cleanup both logs in one transaction
CREATE OR REPLACE FUNCTION public.sql_firewall_cleanup_all_logs(
    p_activity_retention INTERVAL DEFAULT '30 days',
    p_blocked_retention INTERVAL DEFAULT '90 days'
)
RETURNS TABLE(
    activity_deleted BIGINT,
    blocked_deleted BIGINT,
    total_deleted BIGINT
) AS $$
DECLARE
    v_activity_count BIGINT;
    v_blocked_count BIGINT;
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can cleanup firewall logs'
            USING ERRCODE = '42501';
    END IF;
    
    -- Cleanup activity log
    DELETE FROM public.sql_firewall_activity_log
    WHERE log_time < (pg_catalog.now() - p_activity_retention);
    GET DIAGNOSTICS v_activity_count = ROW_COUNT;
    
    -- Cleanup blocked queries log
    DELETE FROM public.sql_firewall_blocked_queries
    WHERE blocked_at < (pg_catalog.now() - p_blocked_retention);
    GET DIAGNOSTICS v_blocked_count = ROW_COUNT;
    
    RETURN QUERY SELECT 
        v_activity_count,
        v_blocked_count,
        v_activity_count + v_blocked_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

COMMENT ON FUNCTION public.sql_firewall_cleanup_all_logs(INTERVAL, INTERVAL) IS 
'Cleanup both activity and blocked query logs in one transaction. Defaults: activity=30 days, blocked=90 days. Superuser only.';

-- Truncate all logs (emergency cleanup)
CREATE OR REPLACE FUNCTION public.sql_firewall_truncate_logs()
RETURNS TABLE(status TEXT) AS $$
BEGIN
    -- session_user, not current_user: SECURITY DEFINER changes current_user.
    -- pg_catalog.pg_authid.rolsuper is the catalog column behind pg_user.usesuper.
    -- No row, or rolsuper not TRUE, is a denial (missing auth must not pass).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_authid AS a
        WHERE a.rolname = session_user
          AND a.rolsuper IS TRUE
    ) THEN
        RAISE EXCEPTION 'Only superusers can truncate firewall logs'
            USING ERRCODE = '42501';
    END IF;
    
    TRUNCATE TABLE public.sql_firewall_activity_log;
    TRUNCATE TABLE public.sql_firewall_blocked_queries;
    
    RETURN QUERY SELECT 'All firewall logs truncated successfully'::pg_catalog.text;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp;

COMMENT ON FUNCTION public.sql_firewall_truncate_logs() IS 
'Emergency function to truncate ALL firewall logs. Use with caution! Superuser only.';

-- Same PUBLIC-execute revocation as the command/rule functions above.
REVOKE ALL ON FUNCTION public.sql_firewall_cleanup_activity_log(INTERVAL) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_cleanup_blocked_queries(INTERVAL) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_cleanup_all_logs(INTERVAL, INTERVAL) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_truncate_logs() FROM PUBLIC;

-- ========================================
-- SECURITY: REVOKE DIRECT TABLE ACCESS
-- ========================================
-- All interaction with firewall tables must go through SECURITY DEFINER functions
-- This prevents users from tampering with firewall configuration and logs

-- Revoke all privileges on firewall tables from PUBLIC
REVOKE ALL ON TABLE public.sql_firewall_activity_log FROM PUBLIC;
REVOKE ALL ON TABLE public.sql_firewall_blocked_queries FROM PUBLIC;
REVOKE ALL ON TABLE public.sql_firewall_command_approvals FROM PUBLIC;
REVOKE ALL ON TABLE public.sql_firewall_query_fingerprints FROM PUBLIC;
REVOKE ALL ON TABLE public.sql_firewall_regex_rules FROM PUBLIC;

-- Revoke sequence access
REVOKE ALL ON SEQUENCE public.sql_firewall_activity_log_log_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.sql_firewall_blocked_queries_block_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.sql_firewall_command_approvals_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.sql_firewall_query_fingerprints_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.sql_firewall_regex_rules_id_seq FROM PUBLIC;

-- SECURITY: audit data is NOT world-readable.
-- sql_firewall_activity_log stores full query text including literal values;
-- granting SELECT to PUBLIC let the least privileged role in the database read
-- every other role's queries. Same for blocked_queries.
-- Reading these requires an explicit grant by the DBA.

-- Policy tables stay readable: the extension evaluates them over SPI as the
-- CALLING user, so revoking SELECT here would break the firewall itself. The
-- cost is that an attacker can read the rule set; closing that requires the
-- extension to read policy out-of-band (see docs/DESIGN-v2.md section 6.1).
GRANT SELECT ON TABLE public.sql_firewall_command_approvals TO PUBLIC;
GRANT SELECT ON TABLE public.sql_firewall_regex_rules TO PUBLIC;
GRANT SELECT ON TABLE public.sql_firewall_query_fingerprints TO PUBLIC;

-- Configuration changes still require SECURITY DEFINER functions (no INSERT/UPDATE/DELETE)

-- Consumer progress for the current shared-memory ring. Not a durable event
-- queue and not extension configuration data: pg_dump must not reload an old
-- cursor into a new ring. One singleton row, created uninitialized.
-- An already-installed 0.0.1 database does not gain this table on restart;
-- this unreleased build expects a fresh install or the 0.0.0->0.0.1 script.
CREATE TABLE IF NOT EXISTS public.sql_firewall_consumer_checkpoint (
    singleton        integer PRIMARY KEY,
    initialized      boolean NOT NULL,
    ring_generation  numeric(20,0),
    extension_oid    oid,
    next_position    numeric(20,0),
    CONSTRAINT sql_firewall_consumer_checkpoint_singleton CHECK (singleton = 1),
    CONSTRAINT sql_firewall_consumer_checkpoint_metadata CHECK (
        (NOT initialized
            AND ring_generation IS NULL
            AND extension_oid IS NULL
            AND next_position IS NULL)
        OR
        (initialized
            AND ring_generation IS NOT NULL
            AND extension_oid IS NOT NULL
            AND extension_oid <> 0
            AND next_position IS NOT NULL
            AND ring_generation >= 0
            AND ring_generation <= 18446744073709551615
            AND next_position >= 0
            AND next_position <= 18446744073709551615)
    )
);

INSERT INTO public.sql_firewall_consumer_checkpoint (singleton, initialized)
SELECT 1, false
WHERE NOT EXISTS (
    SELECT 1 FROM public.sql_firewall_consumer_checkpoint WHERE singleton = 1
);

COMMENT ON TABLE public.sql_firewall_consumer_checkpoint IS
    'Per-database consumer progress for the current ring generation. Not dumped as extension configuration.';

REVOKE ALL ON TABLE public.sql_firewall_consumer_checkpoint FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:201
-- sql_firewall::sql_firewall_approval_worker_status
CREATE  FUNCTION "sql_firewall_approval_worker_status"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sql_firewall_approval_worker_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:213
-- sql_firewall::sql_firewall_clear_approval_cache
CREATE  FUNCTION "sql_firewall_clear_approval_cache"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sql_firewall_clear_approval_cache_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:146
-- sql_firewall::sql_firewall_pause_approval_worker
CREATE  FUNCTION "sql_firewall_pause_approval_worker"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sql_firewall_pause_approval_worker_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:171
-- sql_firewall::sql_firewall_resume_approval_worker
CREATE  FUNCTION "sql_firewall_resume_approval_worker"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sql_firewall_resume_approval_worker_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:130
-- sql_firewall::sql_firewall_status
CREATE  FUNCTION "sql_firewall_status"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sql_firewall_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/policy_visibility.rs:177
-- sql_firewall::policy_visibility::sql_firewall_policy_changed
CREATE FUNCTION "sql_firewall_policy_changed"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'sql_firewall_policy_changed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/policy_visibility.rs:207
-- requires:
--   firewall_schema
--   sql_firewall_policy_changed


-- Cache invalidation (policy_visibility.rs). ENABLE ALWAYS: these fire even
-- with session_replication_role = replica.
--
-- The BEFORE statement trigger is the writer protection: it runs before the
-- statement changes any row, so a RETURNING expression or an earlier user
-- trigger cannot read and publish this transaction's uncommitted policy. It
-- also covers TRUNCATE, which has no row trigger.
--
-- The AFTER row trigger covers logical replication apply, which fires row
-- triggers but no statement triggers. Both must be present and ENABLE ALWAYS
-- for the shared caches to be used at all (invalidation_triggers_enabled).
CREATE TRIGGER sql_firewall_policy_changing
    BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON public.sql_firewall_command_approvals
    FOR EACH STATEMENT EXECUTE FUNCTION sql_firewall_policy_changed('approvals');
CREATE TRIGGER sql_firewall_policy_changed
    AFTER INSERT OR UPDATE OR DELETE ON public.sql_firewall_command_approvals
    FOR EACH ROW EXECUTE FUNCTION sql_firewall_policy_changed('approvals');
ALTER TABLE public.sql_firewall_command_approvals ENABLE ALWAYS TRIGGER sql_firewall_policy_changing;
ALTER TABLE public.sql_firewall_command_approvals ENABLE ALWAYS TRIGGER sql_firewall_policy_changed;
CREATE TRIGGER sql_firewall_policy_changing
    BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON public.sql_firewall_query_fingerprints
    FOR EACH STATEMENT EXECUTE FUNCTION sql_firewall_policy_changed('fingerprints');
CREATE TRIGGER sql_firewall_policy_changed
    AFTER INSERT OR UPDATE OR DELETE ON public.sql_firewall_query_fingerprints
    FOR EACH ROW EXECUTE FUNCTION sql_firewall_policy_changed('fingerprints');
ALTER TABLE public.sql_firewall_query_fingerprints ENABLE ALWAYS TRIGGER sql_firewall_policy_changing;
ALTER TABLE public.sql_firewall_query_fingerprints ENABLE ALWAYS TRIGGER sql_firewall_policy_changed;
-- A trigger function cannot be called directly; firing does not check EXECUTE.
REVOKE ALL ON FUNCTION sql_firewall_policy_changed() FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:45
-- finalize
-- Runs after the generated administrative functions exist.
-- PUBLIC must not execute pause, resume, detailed status, or cache clearing.
-- The functions also reject a non-superuser session_user at runtime.
REVOKE ALL ON FUNCTION public.sql_firewall_pause_approval_worker() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_resume_approval_worker() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_approval_worker_status() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sql_firewall_clear_approval_cache() FROM PUBLIC;
/* </end connected objects> */

